DROP TABLE A_HabitacionUniversitaria;
DROP TABLE A_Vivienda;
DROP TABLE A_ApartamentoComunidad;
DROP TABLE A_HabitacionFenicia;
DROP TABLE A_HabitacionHostal;
DROP TABLE A_HabitacionHotel;
DROP TABLE A_ResidenciaUniversitaria;
DROP TABLE A_AlquilaDia;
DROP TABLE A_AlquilaMes;
DROP TABLE A_Fenicia;
DROP TABLE A_Hostal;
DROP TABLE A_Hotel;
DROP TABLE A_Disponibilidad;
DROP TABLE A_Reserva;
DROP TABLE A_Habitacion;
DROP TABLE A_VinculadoUniandes;
commit;
