-- 1 VinculadoUniandes
INSERT INTO A_VinculadoUniandes (id, nombre, vinculacion) 
VALUES (Alohandes.nextVal, 'Santiago', 'Estudiante');
insert into A_VinculadoUniandes (id, nombre, vinculacion) values (1, 'Krysta', 'Empleado');
insert into A_VinculadoUniandes (id, nombre, vinculacion) values (2, 'Nat', 'Estudiante');
insert into A_VinculadoUniandes (id, nombre, vinculacion) values (3, 'Basile', 'Acudiente');
insert into A_VinculadoUniandes (id, nombre, vinculacion) values (4, 'Che', 'Estudiante');
insert into A_VinculadoUniandes (id, nombre, vinculacion) values (5, 'Carolina', 'Invitado');
insert into A_VinculadoUniandes (id, nombre, vinculacion) values (6, 'Mariana', 'Empleado');
insert into A_VinculadoUniandes (id, nombre, vinculacion) values (7, 'Lavena', 'Invitado');
insert into A_VinculadoUniandes (id, nombre, vinculacion) values (8, 'Mildrid', 'Acudiente');
insert into A_VinculadoUniandes (id, nombre, vinculacion) values (9, 'Ethe', 'Invitado');
insert into A_VinculadoUniandes (id, nombre, vinculacion) values (10, 'Jozef', 'Acudiente');
insert into A_VinculadoUniandes (id, nombre, vinculacion) values (11, 'Abbott', 'Empleado');
insert into A_VinculadoUniandes (id, nombre, vinculacion) values (12, 'Hermann', 'Estudiante');
insert into A_VinculadoUniandes (id, nombre, vinculacion) values (13, 'Myrvyn', 'Estudiante');
insert into A_VinculadoUniandes (id, nombre, vinculacion) values (14, 'Caterina', 'Invitado');
insert into A_VinculadoUniandes (id, nombre, vinculacion) values (15, 'Benedick', 'Invitado');
insert into A_VinculadoUniandes (id, nombre, vinculacion) values (16, 'Edi', 'Acudiente');
insert into A_VinculadoUniandes (id, nombre, vinculacion) values (17, 'Urbanus', 'Estudiante');
insert into A_VinculadoUniandes (id, nombre, vinculacion) values (18, 'Dolli', 'Estudiante');
insert into A_VinculadoUniandes (id, nombre, vinculacion) values (19, 'Willyt', 'Estudiante');
insert into A_VinculadoUniandes (id, nombre, vinculacion) values (20, 'Pearline', 'Estudiante');
insert into A_VinculadoUniandes (id, nombre, vinculacion) values (21, 'Rowe', 'Estudiante');
insert into A_VinculadoUniandes (id, nombre, vinculacion) values (22, 'Meryl', 'Acudiente');
insert into A_VinculadoUniandes (id, nombre, vinculacion) values (23, 'Ellissa', 'Egresado');
insert into A_VinculadoUniandes (id, nombre, vinculacion) values (24, 'Patty', 'Invitado');
insert into A_VinculadoUniandes (id, nombre, vinculacion) values (25, 'Trudy', 'Invitado');
insert into A_VinculadoUniandes (id, nombre, vinculacion) values (26, 'Pincus', 'Estudiante');
insert into A_VinculadoUniandes (id, nombre, vinculacion) values (27, 'Emanuele', 'Estudiante');
insert into A_VinculadoUniandes (id, nombre, vinculacion) values (28, 'Darby', 'Egresado');
insert into A_VinculadoUniandes (id, nombre, vinculacion) values (29, 'Edith', 'Egresado');
insert into A_VinculadoUniandes (id, nombre, vinculacion) values (30, 'Nathanael', 'Invitado');